require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServerCommandsController do

  # This should return the minimal set of attributes required to create a valid
  # ServerCommand. As you add validations to ServerCommand, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "server" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServerCommandsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all server_commands as @server_commands" do
      server_command = ServerCommand.create! valid_attributes
      get :index, {}, valid_session
      assigns(:server_commands).should eq([server_command])
    end
  end

  describe "GET show" do
    it "assigns the requested server_command as @server_command" do
      server_command = ServerCommand.create! valid_attributes
      get :show, {:id => server_command.to_param}, valid_session
      assigns(:server_command).should eq(server_command)
    end
  end

  describe "GET new" do
    it "assigns a new server_command as @server_command" do
      get :new, {}, valid_session
      assigns(:server_command).should be_a_new(ServerCommand)
    end
  end

  describe "GET edit" do
    it "assigns the requested server_command as @server_command" do
      server_command = ServerCommand.create! valid_attributes
      get :edit, {:id => server_command.to_param}, valid_session
      assigns(:server_command).should eq(server_command)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ServerCommand" do
        expect {
          post :create, {:server_command => valid_attributes}, valid_session
        }.to change(ServerCommand, :count).by(1)
      end

      it "assigns a newly created server_command as @server_command" do
        post :create, {:server_command => valid_attributes}, valid_session
        assigns(:server_command).should be_a(ServerCommand)
        assigns(:server_command).should be_persisted
      end

      it "redirects to the created server_command" do
        post :create, {:server_command => valid_attributes}, valid_session
        response.should redirect_to(ServerCommand.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved server_command as @server_command" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServerCommand.any_instance.stub(:save).and_return(false)
        post :create, {:server_command => { "server" => "invalid value" }}, valid_session
        assigns(:server_command).should be_a_new(ServerCommand)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServerCommand.any_instance.stub(:save).and_return(false)
        post :create, {:server_command => { "server" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested server_command" do
        server_command = ServerCommand.create! valid_attributes
        # Assuming there are no other server_commands in the database, this
        # specifies that the ServerCommand created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ServerCommand.any_instance.should_receive(:update_attributes).with({ "server" => "" })
        put :update, {:id => server_command.to_param, :server_command => { "server" => "" }}, valid_session
      end

      it "assigns the requested server_command as @server_command" do
        server_command = ServerCommand.create! valid_attributes
        put :update, {:id => server_command.to_param, :server_command => valid_attributes}, valid_session
        assigns(:server_command).should eq(server_command)
      end

      it "redirects to the server_command" do
        server_command = ServerCommand.create! valid_attributes
        put :update, {:id => server_command.to_param, :server_command => valid_attributes}, valid_session
        response.should redirect_to(server_command)
      end
    end

    describe "with invalid params" do
      it "assigns the server_command as @server_command" do
        server_command = ServerCommand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServerCommand.any_instance.stub(:save).and_return(false)
        put :update, {:id => server_command.to_param, :server_command => { "server" => "invalid value" }}, valid_session
        assigns(:server_command).should eq(server_command)
      end

      it "re-renders the 'edit' template" do
        server_command = ServerCommand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServerCommand.any_instance.stub(:save).and_return(false)
        put :update, {:id => server_command.to_param, :server_command => { "server" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested server_command" do
      server_command = ServerCommand.create! valid_attributes
      expect {
        delete :destroy, {:id => server_command.to_param}, valid_session
      }.to change(ServerCommand, :count).by(-1)
    end

    it "redirects to the server_commands list" do
      server_command = ServerCommand.create! valid_attributes
      delete :destroy, {:id => server_command.to_param}, valid_session
      response.should redirect_to(server_commands_url)
    end
  end

end
